default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { 'postgres' } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: name_development

test:
  <<: *default
  database: name_test

production:
  <<: *default
  database: name_production
  username: name
  password: <%= ENV['NAME_DATABASE_PASSWORD'] %>
